"""Profile-driven Static Mesh audit orchestration."""

from .audit import audit_assets, build_report_from_collection
from .batching import BatchedCollectionResult, BatchProgress, collect_in_batches
from .benchmark import BENCHMARK_VERSION, run_benchmark
from .collectors import CollectionBatch, FixtureCollector, MetadataCollector, UnrealCppCollector
from .contracts import AuditProfile, CollectionFailure, Evidence, Issue, Report, StaticMeshMetadata
from .delivery_groups import (
    DELIVERY_GROUP_VIEW_VERSION,
    DeliveryGroupError,
    build_delivery_group_view,
    delivery_group_path,
    write_delivery_group_view,
)
from .handoff import HANDOFF_VERSION, HandoffError, HandoffResult, export_handoff
from .panel_task import (
    TASK_STATE_VERSION,
    PanelAuditTask,
    request_panel_cancel,
    start_panel_task,
)
from .profile_standards import (
    ProfileChange,
    ProfileValidation,
    clone_as_project_profile,
    diff_profiles,
    save_project_profile,
    validate_profile,
)
from .review_ledger import (
    REVIEW_DECISIONS,
    REVIEW_LEDGER_VERSION,
    REVIEW_VIEW_VERSION,
    ReviewLedgerError,
    ReviewSnapshot,
    load_review_snapshot,
    review_ledger_path,
    update_review,
    write_review_view,
)
from .sessions import (
    COMPARISON_VERSION,
    SESSION_INDEX_VERSION,
    SessionComparison,
    SessionError,
    SessionStore,
    compare_reports,
)
from .texture_audit import audit_textures, build_texture_report_from_collection
from .texture_collectors import (
    TextureFixtureCollector,
    TextureMetadataCollector,
    TextureUnrealCppCollector,
)
from .texture_contracts import (
    TEXTURE_FIXTURE_VERSION,
    TEXTURE_PROFILE_VERSION,
    TEXTURE_REPORT_VERSION,
    Texture2DMetadata,
    TextureAuditProfile,
    TextureAuditReport,
)
from .unattended import (
    EXIT_COLLECTION_FAILED,
    EXIT_CONFIG_ERROR,
    EXIT_PASSED,
    EXIT_POLICY_FAILED,
    EXIT_RUNTIME_ERROR,
    PRESET_VERSION,
    SUMMARY_VERSION,
    PresetError,
    ProjectPreset,
    resolve_asset_paths,
    run_project_preset,
)

__all__ = [
    "BENCHMARK_VERSION",
    "COMPARISON_VERSION",
    "DELIVERY_GROUP_VIEW_VERSION",
    "EXIT_COLLECTION_FAILED",
    "EXIT_CONFIG_ERROR",
    "EXIT_PASSED",
    "EXIT_POLICY_FAILED",
    "EXIT_RUNTIME_ERROR",
    "HANDOFF_VERSION",
    "PRESET_VERSION",
    "REVIEW_DECISIONS",
    "REVIEW_LEDGER_VERSION",
    "REVIEW_VIEW_VERSION",
    "SESSION_INDEX_VERSION",
    "SUMMARY_VERSION",
    "TASK_STATE_VERSION",
    "TEXTURE_FIXTURE_VERSION",
    "TEXTURE_PROFILE_VERSION",
    "TEXTURE_REPORT_VERSION",
    "AuditProfile",
    "BatchProgress",
    "BatchedCollectionResult",
    "CollectionBatch",
    "CollectionFailure",
    "DeliveryGroupError",
    "Evidence",
    "FixtureCollector",
    "HandoffError",
    "HandoffResult",
    "Issue",
    "MetadataCollector",
    "PanelAuditTask",
    "PresetError",
    "ProfileChange",
    "ProfileValidation",
    "ProjectPreset",
    "Report",
    "ReviewLedgerError",
    "ReviewSnapshot",
    "SessionComparison",
    "SessionError",
    "SessionStore",
    "StaticMeshMetadata",
    "Texture2DMetadata",
    "TextureAuditProfile",
    "TextureAuditReport",
    "TextureFixtureCollector",
    "TextureMetadataCollector",
    "TextureUnrealCppCollector",
    "UnrealCppCollector",
    "audit_assets",
    "audit_textures",
    "build_delivery_group_view",
    "build_report_from_collection",
    "build_texture_report_from_collection",
    "clone_as_project_profile",
    "collect_in_batches",
    "compare_reports",
    "delivery_group_path",
    "diff_profiles",
    "export_handoff",
    "load_review_snapshot",
    "request_panel_cancel",
    "resolve_asset_paths",
    "review_ledger_path",
    "run_benchmark",
    "run_project_preset",
    "save_project_profile",
    "start_panel_task",
    "update_review",
    "validate_profile",
    "write_delivery_group_view",
    "write_review_view",
]
